### ISSUE TITLE
Readability ?

### ISSUE THREAD

**Issue by golgote** [benschulz/ko-data-source#1]
I don't see how using arrow syntax improves readability ?
Would it be possible to have some good ol' javascript examples because it is quite frustrating to try to use your grid at the moment. Your examples use requireJS everywhere and callbacks calling other callbacks passed as arguments to some magic factory functions which is maybe very clever, but also totally unreadable for the profane. It is a shame, given the quality of your grid components.
Thank you.

**Comment by benschulz** [comment]
Your point is well taken. How about I add a really plain example? Will you be using RequireJS at all or would you prefer a _no-rjs-at-all_ example? I'll eventually add both, but I'd like to get you what you need asap. The difference, in case you're wondering, is in how/where grid configurations go.

**Comment by golgote** [comment]
Thanks. I would prefer a no-rejs-at-all example. The generic datasource factory example here https://github.com/benschulz/ko-grid-examples/blob/master/src/data/generic-data-source-factory.js hurts my brain. I figured out the promise and the arrow syntax but it gets more complicated after. I am attempting to fetch json data remotely using ajax (probably jquery flavor).

**Comment by benschulz** [comment]
Alright, I added two simple rjs-free examples. I suppose the "server-side" one will be of most interest to you. You can find them under [src/sscces](https://github.com/benschulz/ko-grid-examples/tree/master/src/sscces) in the [ko-grid-examples repository
](https://github.com/benschulz/ko-grid-examples), they are also live on the repositories pages ([client-side](http://benschulz.github.io/ko-grid-examples/sscces/simple-client-side-grid/example.html), ["server-side"](http://benschulz.github.io/ko-grid-examples/sscces/simple-server-side-grid/example.html)).

Please feel free to reopen the issue if more or better detailed examples are needed.
